unset(../components/cosmotrace/raytrace.h CACHE)
if(EXISTS ../components/cosmotrace/raytrace.h)
  add_definitions(-DUSE_COSMOTRACE=1)
else()
  add_definitions(-DUSE_COSMOTRACE=0)
  message(WARNING "${Yellow}Compiling without raytracing support; some features may not work. \n (did you run `git submodule update --init --recursive` ?)${ColorReset}")
endif()
