unset(../components/elliptic_solver/multigrid.h CACHE)
if(EXISTS ../components/elliptic_solver/multigrid.h)
  add_definitions(-DUSE_MULTIGRID=1)
else()
  add_definitions(-DUSE_MULTIGRID=0)
  message(WARNING "${Yellow}Compiling without multigrid support; some features may not work. \n (did you run `git submodule update --init --recursive` ?)${ColorReset}")
endif()

unset(MULTIGRID_SOURCES CACHE)
file(GLOB MULTIGRID_SOURCES components/elliptic_solver/multigrid.cpp)
